In [1]:
 import numpy as np
x = np.array([1,2,3])
print(x.shape)
my_arr = np.arange(45).reshape(9,5)
print(my_arr)

(3,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]


In [14]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
a[3:7:2]

array([3, 5])

In [21]:
my_arr[0:2, 0:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [33]:
matrix = np.arange(54).reshape(6,9)
matrix
matrix[3:6, 5:9]
print("QW4HD DQCRG HM64M 6GJRK 8K83T")

QW4HD DQCRG HM64M 6GJRK 8K83T


In [53]:
#row, column(size of picture) and depth(number of pictures)
matrix_3D = np.arange(27).reshape(3,3,3)
print(matrix_3D)
print(matrix.shape)
print(matrix_3D.ndim)
matrix_3D[2,1,2]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
(6, 9)
3


23

In [ ]:
#Slicing [leave starting one : Take starting one]

In [1]:
matrix_3D[0, 0:1, 0:2] = 7
matrix_3D

NameError: name 'matrix_3D' is not defined

In [71]:
np.linspace(0.5,1.5,11)

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5])

In [96]:
arr_4D = np.arange(20).reshape(4,5)
a= arr_4D[:,2:3] = 0.21
a

array([[ 0,  1,  0,  3,  4],
       [ 5,  6,  0,  8,  9],
       [10, 11,  0, 13, 14],
       [15, 16,  0, 18, 19]])

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a[a>5]

array([6, 7, 8, 9])

In [11]:
list_1 = [0,1,2,3,4,5]
list_2 = []
for i in list_1:
    if i>2:
        list_2.append(i)
print(list_2)

[3, 4, 5]
