In [1]:
#np.size(name of matrix)
#np.shape#for order
#np.size(m, 0 or 1)
#0 for horizontal
#1 for vertical
#All items in row 1:
#m[1,]

In [8]:
import numpy as np
a = np.arange(5)
print(a)
print(a<2)
print(a)
(a<=2) | (a<4)

[0 1 2 3 4]
[ True  True False False False]
[0 1 2 3 4]


array([ True,  True,  True,  True, False])

In [12]:
def work(x):
    return x>=3 or x<3
np.vectorize(work)(a)#Boolean array

array([ True,  True,  True,  True,  True])

In [14]:
r= a<3
a[r]

array([0, 1, 2])

In [26]:
arr = np.arange(30)
print(arr)
np.sum(arr<20)
np.sum(arr[arr<20])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


190

In [35]:
matrix = np.arange(27).reshape(3,3,3)
print(matrix)
y = matrix.flatten()#in memory changes
print(y)
z = matrix.ravel()# change of shape
z

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [38]:
matrix.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [40]:
np.transpose(matrix)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [59]:
matrix1= np.arange(9).reshape(3,3)
print(matrix1)
matrix2= np.arange(10,19).reshape(3,3)
print(matrix2)
matrix3= np.arange(20,29).reshape(3,3)
print(matrix3)
print(np.hstack((matrix1,matrix2,matrix3)))
print(np.vstack((matrix1,matrix2,matrix3)))
print(np.concatenate((matrix1,matrix2,matrix3)))
print(np.dstack((matrix1,matrix2,matrix3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[20 21 22]
 [23 24 25]
 [26 27 28]]
[[ 0  1  2 10 11 12 20 21 22]
 [ 3  4  5 13 14 15 23 24 25]
 [ 6  7  8 16 17 18 26 27 28]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [20 21 22]
 [23 24 25]
 [26 27 28]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [20 21 22]
 [23 24 25]
 [26 27 28]]
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]

 [[ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]]]


In [65]:
mat = np.arange(16).reshape(4,4)
print(mat)
size =np.size(mat)
size
#np.hsplit(mat,size-1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


16

In [71]:
mat.min()
mat.max()
mat.argmin()
mat.argmax()
print(mat.min(axis = 0))
mat.min(axis = 1)
mat.std()
mat.prod()
(mat>10).any()
(mat<10).all()

[0 1 2 3]


array([ 0,  4,  8, 12])