In [2]:
import numpy as np
a = np.ones((2,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
b = np.ones_like(a)
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
arr = np.full((3,4), 10)
arr

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [9]:
identity = np.identity(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
arr_1 = np.array([True , False])
print(arr_1)
Convert_int = arr_1.astype("int")
Convert_int

[ True False]


array([1, 0])

In [19]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names)
names == 'Bob'

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


array([ True, False, False,  True, False, False, False])

In [24]:
data = np.arange(28).reshape(7,4)
print(data)
data[names == 'Bob']

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [26]:
fancy = np.arange(20).reshape(5,4)
fancy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [35]:
fancy[[0,3,4], [1,2,3]]

array([ 1, 14, 19])

In [39]:
a = [2,4,6,8]
b = ['x','y','z','a']
c = zip(a,b)
list(c)

[(2, 'x'), (4, 'y'), (6, 'z'), (8, 'a')]

In [56]:
arr = np.arange(25).reshape(5,5)
print(arr)
# for i in range(5):
#     arr[i] = i+1
# arr

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [54]:
arr[[0,1,2,3]][1:3, [1,2,3]]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [57]:
arr.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [59]:
a = np.dot(arr.T, arr)
a

array([[ 750,  800,  850,  900,  950],
       [ 800,  855,  910,  965, 1020],
       [ 850,  910,  970, 1030, 1090],
       [ 900,  965, 1030, 1095, 1160],
       [ 950, 1020, 1090, 1160, 1230]])

In [71]:
arr_3D = np.arange(16).reshape(2,2,4)
arr_3D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [73]:
arr_3D.transpose(1,2,0)

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [75]:
arr_3D.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [79]:
arr_1 = np.arange(5)
arr_1

array([0, 1, 2, 3, 4])

In [80]:
np.sqrt(arr_1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [82]:
np.exp(arr_1)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [92]:
a = np.arange(10)*2
b = np.arange(10)
print(a,b)
np.maximum(a,b)

[ 0  2  4  6  8 10 12 14 16 18] [0 1 2 3 4 5 6 7 8 9]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [93]:
x, y=np.modf(a)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [94]:
y

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [8]:
a = np.arange(16).reshape(4,4)
a
a[:] = 10
a

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [11]:
x= np.full((4,5), 10)
x

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])